-- Projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Curriculum table
CREATE TABLE IF NOT EXISTS curriculum (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('education', 'experience', 'skill')),
  title TEXT NOT NULL,
  description TEXT,
  start_year INTEGER,
  end_year INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Testimonials table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  text TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

-- Policies for public read access
CREATE POLICY "Allow public read access on projects"
  ON projects FOR SELECT USING (true);

CREATE POLICY "Allow public read access on curriculum"
  ON curriculum FOR SELECT USING (true);

CREATE POLICY "Allow public read access on approved testimonials"
  ON testimonials FOR SELECT USING (is_approved = true);

-- Policies for admin write access (requires authentication)
-- Note: In a real app, you'd want more specific policies based on user roles
CREATE POLICY "Allow authenticated insert on projects"
  ON projects FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update on projects"
  ON projects FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on curriculum"
  ON curriculum FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update on curriculum"
  ON curriculum FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on testimonials"
  ON testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow public insert on testimonials"
  ON testimonials FOR INSERT WITH CHECK (is_approved = false);

CREATE POLICY "Allow authenticated update on testimonials"
  ON testimonials FOR UPDATE USING (auth.role() = 'authenticated');

-- Create storage bucket for project images
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO NOTHING;

-- Policy for public read access to storage
CREATE POLICY "Allow public read access to project images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'project-images');

-- Policy for authenticated upload to project images
CREATE POLICY "Allow authenticated upload to project images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'project-images' AND auth.role() = 'authenticated');